version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '4201:5432'
    environment:
      POSTGRES_DB: www
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bandapixels
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
